name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn test

  test-no-lock:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Test
        run: yarn test
